# Use MySQL for storage
# MySQL version 14.14 in development
#
# Tuesday, 28 July, 2015 12:43
#

default: &default
  adapter: mysql
  encoding: ascii
  pool: 5
  timeout: 5000
  host: localhost
  username: alexander
  password: AXnR4xpyE5kWMew6tR

development:
  <<: *default
  database: HoA_Development

test:
  <<: *default
  database: HoA_Test

production:
  <<: *default
  database: HoA_Production
